### ISSUE TITLE
renaming node, renaming topics does not work as expected

### ISSUE THREAD

**Issue by ace-at-git** [alspitz/cpu_monitor#8]
I have a distributed ROS system with three computers. I would like to start on every computer the cpu_monitor under a different name. In the launch files on the different machines I set up the following:

1. \<node pkg="cpu_monitor" name="**computer1**_cpu_monitor" type="monitor.py" output="screen"\>
2. \<node pkg="cpu_monitor" name="**computer2**_cpu_monitor" type="monitor.py" output="screen"\>
3. \<node pkg="cpu_monitor" name="**computer3**_cpu_monitor" type="monitor.py" output="screen"\>

Unfortunately on all three computers still the same topic "namespace" is used and brings the same topic names like:
`/cpu_monitor/total_cpu`
instead of
`/computer1_cpu_monitor/total_cpu`
`/computer2_cpu_monitor/total_cpu`
`/computer3_cpu_monitor/total_cpu`

Looking in the script I found that topic prefix is hard coded. In order solve this I applied the following patch:

```diff --git a/monitor.py b/monitor.py
index 4671a9c..f7bccb7 100755
--- a/monitor.py
+++ b/monitor.py
@@ -24,8 +24,8 @@ class Node:
   def __init__(self, name, pid):
     self.name = name
     self.proc = psutil.Process(pid)
-    self.cpu_publisher = rospy.Publisher(ns_join("cpu_monitor", name[1:], "cpu"), Float32, queue_size=20)
-    self.mem_publisher = rospy.Publisher(ns_join("cpu_monitor", name[1:], "mem"), UInt64, queue_size=20)
+    self.cpu_publisher = rospy.Publisher(ns_join(rospy.get_name(), name[1:], "cpu"), Float32, queue_size=20)
+    self.mem_publisher = rospy.Publisher(ns_join(rospy.get_name(), name[1:], "mem"), UInt64, queue_size=20)
 
   def publish(self):
     self.cpu_publisher.publish(Float32(self.proc.cpu_percent()))
@@ -45,7 +45,7 @@ if __name__ == "__main__":
   node_map = {}
   ignored_nodes = set()
 
-  cpu_publish = rospy.Publisher("cpu_monitor/total_cpu", Float32, queue_size=20)
+  cpu_publish = rospy.Publisher("%s/total_cpu" % rospy.get_name() ,Float32, queue_size=20)
 
   mem_topics = ["available", "used", "free", "active", "inactive", "buffers", "cached", "shared", "slab"]
 
@@ -54,7 +54,7 @@ if __name__ == "__main__":
 
   mem_publishers = []
   for mem_topic in mem_topics:
-    mem_publishers.append(rospy.Publisher("cpu_monitor/total_%s_mem" % mem_topic,
+    mem_publishers.append(rospy.Publisher("%s/total_%s_mem" % (rospy.get_name(),  mem_topic),
                                           UInt64, queue_size=20))
 
   while not rospy.is_shutdown():
```

**Comment by alspitz** [comment]
Thanks for bringing this up. I've pushed commit https://github.com/alspitz/cpu_monitor/commit/e14953bc108b943fed556fbd6344cd61a9291551 which uses the private name space, and will cause all topic names to fall under the node name. I believe that's simplest unless there is some benefit to calling get_name directly?

**Comment by ace-at-git** [comment]
I tested your commit - perfect, I like your smart implementation!
